import js from '@eslint/js'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'
// Last in every `extends` chain below: it only turns rules *off*, so anything after it would
// re-enable the formatting rules Prettier already owns and produce two sources of truth.
import prettier from 'eslint-config-prettier/flat'

export default tseslint.config(
  { ignores: ['dist', 'coverage', 'node_modules', 'playwright-report', 'test-results'] },

  // Application source. Type-aware linting is deliberately not enabled: `npm run typecheck`
  // already runs the full compiler, and the type-aware rule set costs several seconds per run
  // to re-derive what tsc just proved.
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      // `configs.flat[...]`, not `configs[...]`. In eslint-plugin-react-hooks v7 the
      // top-level key is still the eslintrc shape, whose `plugins` is an array of
      // strings; flat config wants an object and refuses to load at all otherwise --
      // with an error about *your* config, not the plugin's.
      reactHooks.configs.flat['recommended-latest'],
      jsxA11y.flatConfigs.recommended,
      prettier,
    ],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
    },
    // `jsx-a11y` matches control elements by tag name, so a `<label>` wrapping one
    // of this app's own atoms reads to it as a label wrapping nothing. Naming them
    // here is the plugin's supported answer and is better than the alternative at
    // each call site, which is an `eslint-disable` on the very rule that catches
    // the mistake this one is not making.
    settings: {
      'jsx-a11y': {
        components: {
          Checkbox: 'input',
          Input: 'input',
          Textarea: 'textarea',
        },
      },
    },
    plugins: {
      'react-refresh': reactRefresh,
    },
    rules: {
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // `_`-prefixed is the repository's marker for "deliberately unused" -- a caught error we
      // do not inspect, a positional parameter we must accept to reach the next one.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },

  // shadcn's atoms. Every one of them exports its `cva` variants object beside the
  // component -- `buttonVariants` is imported by anything that needs to look like a
  // button without being one -- which trips react-refresh/only-export-components.
  // The cost is losing fast refresh for that one file when it is edited, and these
  // files are generated by `shadcn add` and edited about once a wave. Turning the
  // rule off here is cheaper than re-patching each atom on arrival for eight waves.
  {
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // Config files run in Node, not in the browser.
  {
    files: ['*.config.{ts,js}', 'vitest.setup.ts'],
    extends: [js.configs.recommended, tseslint.configs.recommended, prettier],
    languageOptions: { globals: globals.node },
  },

  // Playwright specs. Node globals for `process.env`, and none of the React
  // rules -- there is no component here, and `jsx-a11y` has no JSX to read.
  {
    files: ['e2e/**/*.ts'],
    extends: [js.configs.recommended, tseslint.configs.recommended, prettier],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
)
