-- =====================================================================================
--  V1__baseline.sql — the whole SlotFlow v1 schema, in one greenfield migration.
--
--  THIS FILE IS IMMUTABLE. The moment it has run anywhere, Flyway has recorded its
--  checksum. Every later change is a new V2__/V3__ file — never an edit to this one.
--
--  Amended once, before any merge to main and before any deployment, to close five defects a
--  review of wave 1 found: the blocked-range CHECK did not pin the buffers, nothing kept a
--  tenant's rows inside its own tenant, a PENDING row could carry no expiry, and three foreign
--  keys had no usable index. Every local volume was recreated at the same time. The rule above
--  applies from that point on.
--
--  Conventions held throughout:
--    * ids are uuid and generated by the application, so an aggregate can be assembled
--      before it is flushed
--    * every point in time is timestamptz (UTC at rest, UTC on the wire); only the
--      recurring wall-clock rules use date/time, because "09:00 on Tuesdays" is a local
--      concept that has to survive a DST change
--    * enums are stored as their string name and pinned by CHECK — ordinals are a future
--      outage the day someone reorders a Java enum
--    * money is integer minor units; there is no floating point anywhere near a price
--    * integer/bigint/varchar are chosen to match what Hibernate expects, so
--      ddl-auto: validate stays green from plan 03 onwards
-- =====================================================================================

-- Not optional. A GiST index cannot do plain equality on a uuid, so `staff_id WITH =` in
-- the exclusion constraint at the bottom of this file is impossible without btree_gist.
-- Missing extension fails the ALTER TABLE, not the first overlapping insert.
CREATE EXTENSION IF NOT EXISTS btree_gist;


-- =====================================================================================
--  TENANCY
-- =====================================================================================

CREATE TABLE business (
    id               uuid         PRIMARY KEY,
    slug             varchar(40)  NOT NULL,
    name             varchar(120) NOT NULL,
    timezone         varchar(64)  NOT NULL,
    currency         varchar(3)   NOT NULL,
    deposit_required boolean      NOT NULL DEFAULT false,
    deposit_percent  integer      NOT NULL DEFAULT 0,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    updated_at       timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT business_slug_key UNIQUE (slug),
    -- The slug is the public URL segment, so it is lowercase and URL-safe by constraint
    -- rather than by convention.
    CONSTRAINT business_slug_format_chk CHECK (slug ~ '^[a-z0-9-]{3,40}$'),
    CONSTRAINT business_currency_format_chk CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT business_deposit_percent_chk CHECK (deposit_percent BETWEEN 0 AND 100)
);

COMMENT ON COLUMN business.timezone IS
    'IANA zone id (e.g. Europe/Paris). Frames the business day; the wire stays UTC.';

-- One policy per business, and no policy without a business: the FK is the PK.
CREATE TABLE booking_policy (
    business_id               uuid        PRIMARY KEY REFERENCES business (id) ON DELETE CASCADE,
    min_lead_time_hours       integer     NOT NULL DEFAULT 2,
    max_advance_days          integer     NOT NULL DEFAULT 60,
    cancellation_cutoff_hours integer     NOT NULL DEFAULT 24,
    slot_granularity_minutes  integer     NOT NULL DEFAULT 15,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT booking_policy_lead_chk        CHECK (min_lead_time_hours >= 0),
    CONSTRAINT booking_policy_advance_chk     CHECK (max_advance_days > 0),
    CONSTRAINT booking_policy_cutoff_chk      CHECK (cancellation_cutoff_hours >= 0),
    CONSTRAINT booking_policy_granularity_chk CHECK (slot_granularity_minutes > 0
                                                     AND slot_granularity_minutes <= 480)
);


-- =====================================================================================
--  IDENTITY
--  `user` is reserved in Postgres, hence app_user. Roles are OWNER and STAFF only (D1):
--  every booking is a guest booking, so there is no customer account to model.
-- =====================================================================================

CREATE TABLE app_user (
    id            uuid         PRIMARY KEY,
    -- NOT NULL by D1: a user always belongs to exactly one business.
    business_id   uuid         NOT NULL REFERENCES business (id) ON DELETE CASCADE,
    email         varchar(320) NOT NULL,
    -- Null until an invited staff member accepts and chooses one (plan 06).
    password_hash varchar(100),
    full_name     varchar(120) NOT NULL,
    role          varchar(16)  NOT NULL,
    active        boolean      NOT NULL DEFAULT true,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),

    -- Globally unique, not unique-per-business (D13): invitations are accepted at an
    -- address, and one human cannot own two businesses in v1.
    CONSTRAINT app_user_email_key       UNIQUE (email),
    -- Stored lowercase so the unique index is the case-insensitive check, with no
    -- functional index and no CITEXT dependency.
    CONSTRAINT app_user_email_lower_chk CHECK (email = lower(email)),
    CONSTRAINT app_user_role_chk        CHECK (role IN ('OWNER', 'STAFF')),
    -- Redundant against the primary key, and not decoration: it is the only thing that lets
    -- another table point at (id, business_id) and so inherit "this user is in that tenant" as a
    -- referential guarantee rather than as an application check. See staff_service and booking.
    CONSTRAINT app_user_id_business_key UNIQUE (id, business_id)
);

CREATE INDEX app_user_business_idx ON app_user (business_id);


-- =====================================================================================
--  CATALOG
--  `service` would collide with @Service in the Java package it lives in (D8), so the
--  table is service_offering. The REST path stays /api/services.
-- =====================================================================================

CREATE TABLE service_offering (
    id                    uuid         PRIMARY KEY,
    business_id           uuid         NOT NULL REFERENCES business (id) ON DELETE CASCADE,
    name                  varchar(120) NOT NULL,
    description           text,
    duration_minutes      integer      NOT NULL,
    price_cents           bigint       NOT NULL,
    buffer_before_minutes integer      NOT NULL DEFAULT 0,
    buffer_after_minutes  integer      NOT NULL DEFAULT 0,
    active                boolean      NOT NULL DEFAULT true,
    created_at            timestamptz  NOT NULL DEFAULT now(),
    updated_at            timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT service_offering_duration_chk CHECK (duration_minutes > 0),
    CONSTRAINT service_offering_price_chk    CHECK (price_cents >= 0),
    CONSTRAINT service_offering_buffers_chk  CHECK (buffer_before_minutes >= 0
                                                    AND buffer_after_minutes >= 0),
    -- The FK target that keeps a service and whoever performs it in the same tenant; see
    -- app_user_id_business_key for the reasoning.
    CONSTRAINT service_offering_id_business_key UNIQUE (id, business_id)
);

CREATE INDEX service_offering_business_idx ON service_offering (business_id);

-- Which staff member can perform which service. Both sides cascade: the join row carries
-- no information of its own.
--
-- business_id is not denormalisation for reading -- nothing selects it. It exists so both
-- foreign keys can be composite, which is what makes a cross-tenant assignment
-- unrepresentable rather than merely rejected by a service class: with plain (staff_id) and
-- (service_id) keys, staff_service(staff-of-business-A, service-of-business-B) satisfies both
-- FKs and commits, and the availability engine then offers another tenant's staff on this
-- tenant's public booking page. One column plus two composite keys is the whole fix, and it
-- holds for every writer -- including psql and any future batch import.
CREATE TABLE staff_service (
    business_id uuid NOT NULL REFERENCES business (id) ON DELETE CASCADE,
    staff_id    uuid NOT NULL,
    service_id  uuid NOT NULL,

    CONSTRAINT staff_service_pkey PRIMARY KEY (staff_id, service_id),
    -- Each half has to resolve to a row that is in *this* business.
    CONSTRAINT staff_service_staff_fkey FOREIGN KEY (staff_id, business_id)
        REFERENCES app_user (id, business_id) ON DELETE CASCADE,
    CONSTRAINT staff_service_service_fkey FOREIGN KEY (service_id, business_id)
        REFERENCES service_offering (id, business_id) ON DELETE CASCADE
);

-- The PK covers staff -> services; this covers "who can perform this service", which is
-- what the public booking flow asks (D9). It also serves the (service_id, business_id)
-- cascade check, as a leading-column prefix.
CREATE INDEX staff_service_service_idx ON staff_service (service_id);
-- Deleting a business reaches these rows directly as well as through app_user and
-- service_offering, and that direct path has no other index to use.
CREATE INDEX staff_service_business_idx ON staff_service (business_id);


-- =====================================================================================
--  AVAILABILITY
-- =====================================================================================

-- The weekly recurring template. Local times on purpose: 09:00 stays 09:00 across a DST
-- boundary, which is what a business actually means by "we open at nine".
CREATE TABLE working_hours (
    id          uuid        PRIMARY KEY,
    staff_id    uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    -- The java.time.DayOfWeek name, not 0-6: no off-by-one between Java and SQL, ever.
    day_of_week varchar(9)  NOT NULL,
    start_time  time        NOT NULL,
    end_time    time        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT working_hours_day_chk CHECK (day_of_week IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    -- end < start legitimately means "crosses midnight", so only equality is meaningless.
    CONSTRAINT working_hours_span_chk CHECK (start_time <> end_time)
);

CREATE INDEX working_hours_staff_day_idx ON working_hours (staff_id, day_of_week);

-- Holidays, one-off blocks and extra hours. Named override rather than exception (D8):
-- AvailabilityException reads as a throwable in Java.
CREATE TABLE availability_override (
    id          uuid         PRIMARY KEY,
    business_id uuid         NOT NULL REFERENCES business (id) ON DELETE CASCADE,
    -- NULL = business-wide closure applying to every staff member (D5). "Closed Christmas
    -- Day" is one row that cannot drift as staff join and leave.
    staff_id    uuid         REFERENCES app_user (id) ON DELETE CASCADE,
    date        date         NOT NULL,
    start_time  time,
    end_time    time,
    type        varchar(8)   NOT NULL,
    reason      varchar(200),
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT availability_override_type_chk  CHECK (type IN ('BLOCKED', 'EXTRA')),
    -- Both null = whole day. One of the two null is a bug, never a meaning.
    CONSTRAINT availability_override_times_chk CHECK ((start_time IS NULL) = (end_time IS NULL)),
    CONSTRAINT availability_override_span_chk  CHECK (start_time IS NULL OR start_time <> end_time),
    -- A whole-day BLOCKED is a day off; a whole-day EXTRA says nothing at all.
    CONSTRAINT availability_override_extra_chk CHECK (type <> 'EXTRA' OR start_time IS NOT NULL)
);

CREATE INDEX availability_override_staff_date_idx ON availability_override (staff_id, date);
CREATE INDEX availability_override_business_date_idx ON availability_override (business_id, date);
-- Business-wide closures are read on every availability query, for every staff member. The
-- query is `business_id = ? AND staff_id IS NULL AND date BETWEEN ? AND ?`, so business_id
-- leads: on (date) alone, every other tenant's closures for those dates are scanned and then
-- re-checked, and the cost of the query meant to be fastest grows with the tenant count.
CREATE INDEX availability_override_business_wide_idx
    ON availability_override (business_id, date)
    WHERE staff_id IS NULL;


-- =====================================================================================
--  BOOKING
-- =====================================================================================

CREATE TABLE booking (
    id                    uuid         PRIMARY KEY,
    business_id           uuid         NOT NULL REFERENCES business (id) ON DELETE CASCADE,
    -- NO ACTION rather than CASCADE, so a service or a staff member with booking history
    -- cannot be hard-deleted; plan 07 soft-deletes instead. Deliberately not RESTRICT:
    -- RESTRICT is checked immediately, which would make deleting a whole business fail
    -- depending on the order Postgres happens to cascade in. NO ACTION defers the check to
    -- end of statement, so the CASCADE from business still works and the protection is the
    -- same for a direct DELETE.
    -- Both are composite foreign keys, declared at the bottom of the table rather than
    -- inline, so the service and the staff member are constrained to be *in* business_id --
    -- not merely to exist. Without that, a booking can name another tenant's staff member and
    -- still commit, and no application check stands between a leaked uuid and that row.
    service_id            uuid         NOT NULL,
    staff_id              uuid         NOT NULL,

    -- Guest booking only (D1): no account, no customer_id, just contact details.
    guest_name            varchar(120) NOT NULL,
    guest_email           varchar(320) NOT NULL,
    guest_phone           varchar(32),

    -- What the customer sees.
    starts_at             timestamptz  NOT NULL,
    ends_at               timestamptz  NOT NULL,
    -- What the calendar actually loses: the appointment expanded by its buffers (D4).
    -- Computed by the application at insert, not GENERATED ALWAYS: `timestamptz - interval`
    -- is STABLE, not IMMUTABLE, so Postgres refuses it in a stored generated column.
    blocked_from          timestamptz  NOT NULL,
    blocked_to            timestamptz  NOT NULL,

    status                varchar(16)  NOT NULL,

    -- Terms are snapshotted at creation (D14): editing a service later must not rewrite
    -- the price or the blocked range of appointments already taken.
    price_cents           bigint       NOT NULL,
    deposit_paid_cents    bigint       NOT NULL DEFAULT 0,
    buffer_before_minutes integer      NOT NULL DEFAULT 0,
    buffer_after_minutes  integer      NOT NULL DEFAULT 0,

    stripe_session_id     varchar(255),
    notes                 text,
    -- The customer's only credential for viewing or cancelling their booking.
    cancellation_token    uuid         NOT NULL,
    -- Set only while a deposit is in flight (D3); the sweeper cancels stale rows so an
    -- abandoned checkout cannot hold a slot forever.
    expires_at            timestamptz,
    -- Makes the reminder job idempotent: a resent reminder is a bug, not a retry.
    reminder_sent_at      timestamptz,
    version               bigint       NOT NULL DEFAULT 0,
    created_at            timestamptz  NOT NULL DEFAULT now(),
    updated_at            timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT booking_cancellation_token_key UNIQUE (cancellation_token),
    -- One booking per Stripe Checkout session; makes webhook replay harmless.
    CONSTRAINT booking_stripe_session_key     UNIQUE (stripe_session_id),
    CONSTRAINT booking_status_chk CHECK (status IN
        ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')),
    CONSTRAINT booking_span_chk           CHECK (ends_at > starts_at),
    CONSTRAINT booking_blocked_span_chk   CHECK (blocked_to > blocked_from),
    -- The blocked window is not merely *at least* the appointment: it is exactly the
    -- appointment widened by the buffers snapshotted on this row. Asserting only `>=` lets a
    -- caller store the raw appointment while recording a 10 minute buffer -- which passes every
    -- constraint here and then silently narrows booking_no_overlap back to the unbuffered
    -- window, losing the D4 guarantee this schema exists to provide, with no error anywhere.
    --
    -- make_interval is IMMUTABLE and yields a pure time-of-day interval (no days, no months),
    -- so the arithmetic is exact and independent of the session TimeZone -- checked across the
    -- Europe/Paris spring-forward jump. That is also why this works as a CHECK even though the
    -- `timestamptz - interval` operator is only STABLE, and so could never have been a stored
    -- generated column.
    CONSTRAINT booking_blocked_covers_chk CHECK (
        blocked_from = starts_at - make_interval(mins => buffer_before_minutes)
        AND blocked_to = ends_at + make_interval(mins => buffer_after_minutes)),
    CONSTRAINT booking_price_chk          CHECK (price_cents >= 0),
    CONSTRAINT booking_deposit_chk        CHECK (deposit_paid_cents >= 0
                                                 AND deposit_paid_cents <= price_cents),
    CONSTRAINT booking_buffers_chk        CHECK (buffer_before_minutes >= 0
                                                 AND buffer_after_minutes >= 0),
    -- PENDING means "a deposit is in flight" (D3), and PENDING holds the slot, so a PENDING row
    -- with no expiry holds it forever: the sweeper looks for `expires_at < now()`, NULL < now()
    -- is NULL, so the row never matches while booking_no_overlap keeps honouring it -- an
    -- unbookable slot with no booking visible in any list that filters on CONFIRMED.
    -- Booking.awaitingDeposit already refuses a null expiry; this refuses it for psql and seed
    -- scripts too.
    CONSTRAINT booking_pending_expiry_chk CHECK (status <> 'PENDING' OR expires_at IS NOT NULL),

    -- NO ACTION (the default), for the reason documented on the columns above.
    CONSTRAINT booking_service_fkey FOREIGN KEY (service_id, business_id)
        REFERENCES service_offering (id, business_id),
    CONSTRAINT booking_staff_fkey FOREIGN KEY (staff_id, business_id)
        REFERENCES app_user (id, business_id)
);

COMMENT ON COLUMN booking.blocked_from IS
    'starts_at minus buffer_before_minutes. The exclusion constraint ranges over this.';
COMMENT ON COLUMN booking.blocked_to IS
    'ends_at plus buffer_after_minutes. The exclusion constraint ranges over this.';

-- -------------------------------------------------------------------------------------
--  The double-booking guarantee.
--
--  The application checks availability before inserting, but that check is an
--  optimisation. This constraint is the guarantee: two requests racing for the same slot
--  produce one row and one 23P01, whatever the application believed.
--
--  It ranges over blocked_from/blocked_to rather than starts_at/ends_at (D4) so the
--  database enforces exactly the rule the availability engine applies. A constraint over
--  the raw appointment would happily accept a booking that lands inside another one's
--  cleanup buffer — a row the engine itself would never have offered.
--
--  The WHERE clause is what makes cancelled slots rebookable: only PENDING and CONFIRMED
--  rows occupy a calendar.
-- -------------------------------------------------------------------------------------
ALTER TABLE booking
    ADD CONSTRAINT booking_no_overlap
    EXCLUDE USING gist (
        staff_id                            WITH =,
        tstzrange(blocked_from, blocked_to) WITH &&
    ) WHERE (status IN ('PENDING', 'CONFIRMED'));

-- The availability engine's hot path: active bookings for a set of staff over a date
-- range. Without it every availability query sequentially scans the booking table.
CREATE INDEX booking_staff_active_start_idx ON booking (staff_id, starts_at)
    WHERE status IN ('PENDING', 'CONFIRMED');
-- Admin calendar range queries.
CREATE INDEX booking_business_start_idx ON booking (business_id, starts_at);
-- Keeps the FK to service_offering from having to scan on delete checks.
CREATE INDEX booking_service_idx ON booking (service_id);
-- The same job for the staff FK. It cannot be left to booking_staff_active_start_idx above:
-- that index is partial on PENDING/CONFIRMED, while the referential check runs
-- `WHERE staff_id = $1` with no status predicate and has to see exactly the CANCELLED and
-- COMPLETED history the NO ACTION guard exists to find.
CREATE INDEX booking_staff_idx ON booking (staff_id);
-- The expiry sweeper (D3).
CREATE INDEX booking_pending_expiry_idx ON booking (expires_at)
    WHERE status = 'PENDING';
-- The reminder job: due soon, not yet reminded.
CREATE INDEX booking_reminder_due_idx ON booking (starts_at)
    WHERE status = 'CONFIRMED' AND reminder_sent_at IS NULL;


-- =====================================================================================
--  TOKENS
--  Every table here stores a SHA-256 hash (64 hex characters), never the value that was
--  handed out. A dump of these tables is worth nothing to whoever reads it.
-- =====================================================================================

CREATE TABLE refresh_token (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash  varchar(64) NOT NULL,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    -- The rotation chain. Presenting a token that already has a successor is theft, and
    -- plan 05 revokes the whole chain when it happens.
    replaced_by uuid        REFERENCES refresh_token (id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT refresh_token_hash_key UNIQUE (token_hash)
);

CREATE INDEX refresh_token_user_idx ON refresh_token (user_id);
-- ON DELETE SET NULL on the rotation chain above means every deleted token runs
-- `UPDATE refresh_token SET replaced_by = NULL WHERE replaced_by = $1`. With a 7 day TTL and
-- per-request rotation this is the largest table in the schema, so without this index deleting
-- one user scans all of it once per token that user ever held.
CREATE INDEX refresh_token_replaced_by_idx ON refresh_token (replaced_by);

CREATE TABLE password_reset_token (
    id         uuid        PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT password_reset_token_hash_key UNIQUE (token_hash)
);

CREATE INDEX password_reset_token_user_idx ON password_reset_token (user_id);

-- An invitation is a first-class row against an inactive app_user, not a bare emailed
-- link: it can be listed, resent, expired and consumed exactly once.
CREATE TABLE staff_invitation (
    id          uuid         PRIMARY KEY,
    business_id uuid         NOT NULL REFERENCES business (id) ON DELETE CASCADE,
    user_id     uuid         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    email       varchar(320) NOT NULL,
    token_hash  varchar(64)  NOT NULL,
    expires_at  timestamptz  NOT NULL,
    used_at     timestamptz,
    created_at  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT staff_invitation_hash_key    UNIQUE (token_hash),
    CONSTRAINT staff_invitation_email_lower_chk CHECK (email = lower(email))
);

CREATE INDEX staff_invitation_user_idx     ON staff_invitation (user_id);
CREATE INDEX staff_invitation_business_idx ON staff_invitation (business_id);
